-- Net Garagem - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2015 


Library IEEE;
Use IEEE.STD_LOGIC_1164.ALL;
Use IEEE.STD_LOGIC_ARITH.ALL;
Use IEEE.STD_LOGIC_UNSIGNED.ALL;


Entity Garagem_main IS
Port(
    Clk : IN STD_LOGIC;
    Enable : IN STD_LOGIC;
    Reset : IN STD_LOGIC
);
End Garagem_main;



Architecture Structural OF Garagem_main IS

  -- Component Definition:
  Component Garagem IS
  Port(
      Clk : IN STD_LOGIC;
      arrive : IN STD_LOGIC;
      got_ticket : IN STD_LOGIC;
      exit : IN STD_LOGIC;
      payment : IN STD_LOGIC;
      gate_in_open : OUT STD_LOGIC;
      get_out_open : OUT STD_LOGIC;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component Garagem;

  -- Internal signals:

BEGIN

    U_Garagem : Garagem Port Map(
        Clk => Clk,
        arrive => '0',
        got_ticket => '0',
        exit => '0',
        payment => '0',
        Enable => Enable,
        Reset => Reset
    );

End Structural;
