-- Net Garagem - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2014 




  -- Component Definition:
  Component Garagem IS
  Port(
      Clk : IN STD_LOGIC;
      arrive : IN STD_LOGIC;
      got_ticket : IN STD_LOGIC;
      exit : IN STD_LOGIC;
      payment : IN STD_LOGIC;
      gate_in_open : OUT STD_LOGIC;
      get_out_open : OUT STD_LOGIC;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component Garagem;



    -- Port Map Template:
    U_Garagem : Garagem Port Map(
        Clk => clk,
        arrive => arrive,
        got_ticket => got_ticket,
        exit => exit,
        payment => payment,
        gate_in_open => gate_in_open,
        get_out_open => get_out_open,
        Enable => enable,
        Reset => reset
    );

